apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app:  server
    spec:
      containers:
      - name:  server
        image:  adityakrmaurya/carparking
        ports:
        - containerPort: 55544
        env:
          - name:  SPRING_DATASOURCE_USERNAME
            value: postgres
          - name:  SPRING_DATASOURCE_PASSWORD
            value: password
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://10.102.2.236:5432/car_database
